apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-example
  annotations:
    github.com/project-slug: sentinelt/backstage-example
    backstage.io/techdocs-ref: file:docs/index.md
    backstage.io/adr-location: file:docs/adrs
spec:
  owner: Sławek
  type: other
  lifecycle: unknown
